// Package adapter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package adapter

// ユーザー新規作成リクエスト
type RequestPostUsers struct {
	// メールアドレス
	Email string `json:"email"`

	// パスワード
	Password string `json:"password"`

	// 確認用パスワード
	PasswordConf string `json:"password_conf"`
}

// ユーザー詳細更新リクエスト
type RequestPutUsers struct {
	// メールアドレス
	Email string `json:"email"`

	// 更新後パスワード
	Password *string `json:"password,omitempty"`

	// 確認用パスワード
	PasswordConf *string `json:"password_conf,omitempty"`
}

// AuthToken defines model for auth_token.
type AuthToken string

// Limit defines model for limit.
type Limit int

// Page defines model for page.
type Page int

// ResponseGetUser defines model for ResponseGetUser.
type ResponseGetUser struct {
	// メールアドレス
	Email string `json:"email"`

	// ユーザーID
	Id string `json:"id"`
}

// ユーザーリスト
type ResponseGetUsers struct {
	List []struct {
		// メールアドレス
		Email string `json:"email"`

		// ユーザーID
		Id string `json:"id"`
	} `json:"list"`

	// ページング情報
	Page struct {
		// 最終ページ
		Last int `json:"last"`

		// 現在位置
		Now int `json:"now"`
	} `json:"page"`
}

// GetV1UsersParams defines parameters for GetV1Users.
type GetV1UsersParams struct {
	// ページャー
	Page *Page `json:"page,omitempty"`

	// 件数
	Limit *Limit `json:"limit,omitempty"`

	// 認証トークン
	AuthToken *AuthToken `json:"auth_token,omitempty"`
}

// PostV1UsersJSONBody defines parameters for PostV1Users.
type PostV1UsersJSONBody RequestPostUsers

// PostV1UsersParams defines parameters for PostV1Users.
type PostV1UsersParams struct {
	// 認証トークン
	AuthToken *AuthToken `json:"auth_token,omitempty"`
}

// DeleteV1UsersUserIdParams defines parameters for DeleteV1UsersUserId.
type DeleteV1UsersUserIdParams struct {
	// 認証トークン
	AuthToken *AuthToken `json:"auth_token,omitempty"`
}

// GetV1UsersUserIdParams defines parameters for GetV1UsersUserId.
type GetV1UsersUserIdParams struct {
	// 認証トークン
	AuthToken *AuthToken `json:"auth_token,omitempty"`
}

// PutV1UsersUserIdJSONBody defines parameters for PutV1UsersUserId.
type PutV1UsersUserIdJSONBody RequestPutUsers

// PutV1UsersUserIdParams defines parameters for PutV1UsersUserId.
type PutV1UsersUserIdParams struct {
	// 認証トークン
	AuthToken *AuthToken `json:"auth_token,omitempty"`
}

// PostV1UsersJSONRequestBody defines body for PostV1Users for application/json ContentType.
type PostV1UsersJSONRequestBody PostV1UsersJSONBody

// PutV1UsersUserIdJSONRequestBody defines body for PutV1UsersUserId for application/json ContentType.
type PutV1UsersUserIdJSONRequestBody PutV1UsersUserIdJSONBody

