// Code generated by MockGen. DO NOT EDIT.
// Source: store.go

// Package usecase is a generated GoMock package.
package usecase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStore) Create(targetAddr interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", targetAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStoreMockRecorder) Create(targetAddr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStore)(nil).Create), targetAddr)
}

// Delete mocks base method.
func (m *MockStore) Delete(targetAddr interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", targetAddr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStoreMockRecorder) Delete(targetAddr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStore)(nil).Delete), targetAddr)
}

// Find mocks base method.
func (m *MockStore) Find(destAddr interface{}, conds string, params ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{destAddr, conds}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Find indicates an expected call of Find.
func (mr *MockStoreMockRecorder) Find(destAddr, conds interface{}, params ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{destAddr, conds}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStore)(nil).Find), varargs...)
}

// FindWithLimitAndOffset mocks base method.
func (m *MockStore) FindWithLimitAndOffset(destAddr interface{}, limit, offset int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithLimitAndOffset", destAddr, limit, offset)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindWithLimitAndOffset indicates an expected call of FindWithLimitAndOffset.
func (mr *MockStoreMockRecorder) FindWithLimitAndOffset(destAddr, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithLimitAndOffset", reflect.TypeOf((*MockStore)(nil).FindWithLimitAndOffset), destAddr, limit, offset)
}

// First mocks base method.
func (m *MockStore) First(destAddr interface{}, conds string, params ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{destAddr, conds}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "First", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// First indicates an expected call of First.
func (mr *MockStoreMockRecorder) First(destAddr, conds interface{}, params ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{destAddr, conds}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*MockStore)(nil).First), varargs...)
}

// Update mocks base method.
func (m *MockStore) Update(targetAddr interface{}, params map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", targetAddr, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStoreMockRecorder) Update(targetAddr, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStore)(nil).Update), targetAddr, params)
}
